### ISSUE TITLE
大佬,如果是细微的滑动,左侧的列表有时候不跟随显示

### ISSUE THREAD

**Issue by zhangqifan1** [PartingSoul/LinkageRecyclerviewDemo#1]
大佬,如果是细微的滑动,左侧的列表有时候不跟随显示.....

**Comment by PartingSoul** [comment]
怎么样的细微滑动？

**Comment by zhangqifan1** [comment]
。。大佬你先滑到一日三餐，然后慢慢往上一个一个的滑，左边有选中效果，但是条目不会smoothToPosition。。。这个现象不知道合理么(●—●)
发件人: "PartingSoul"<notifications@github.com>
发送时间: 2019年7月24日(星期三) 晚上9:52
收件人: "PartingSoul/LinkageRecyclerviewDemo"<LinkageRecyclerviewDemo@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"zhangqifan1"<852780161@qq.com>;
主题: Re: [PartingSoul/LinkageRecyclerviewDemo] 大佬,如果是细微的滑动,左侧的列表有时候不跟随显示 (#1)



怎么样的细微滑动？

**Comment by PartingSoul** [comment]
复现不了你说的效果，我这边往上滑动的效果是右侧RecyclerView的标题item顶部与悬浮标题顶部对齐时，左边对应类别才会选中高亮

**Comment by zhangqifan1** [comment]
大佬，就是先滑倒主食小吃，
然后右面慢慢往上滑，一点一点滑，然后右侧第一个变成主食小吃了，左侧没有跟着。。。。
 
---原始邮件---
发件人: "PartingSoul"<notifications@github.com>
发送时间: 2019年7月24日(星期三) 晚上10:07
收件人: "PartingSoul/LinkageRecyclerviewDemo"<LinkageRecyclerviewDemo@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"zhangqifan1"<852780161@qq.com>;
主题: Re: [PartingSoul/LinkageRecyclerviewDemo] 大佬,如果是细微的滑动,左侧的列表有时候不跟随显示 (#1)



复现不了你说的效果，我这边往上滑动的效果是右侧RecyclerView的标题item顶部与悬浮标题顶部对齐时，左边对应类别才会选中高亮

**Comment by PartingSoul** [comment]
如果方便的话可以录个屏，这是我QQ： 982068238
